version: '3'
services:
  db_in_postgres:
    restart: always
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: my_db_user
      POSTGRES_DB: my_db
      POSTGRES_PASSWORD: my_db_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  db_in_mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'my_db_user'
      MYSQL_PASSWORD: 'my_db_password'
      MYSQL_ROOT_PASSWORD: 'my_db_root_password'
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  app_rails:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOMAIN_CORE_DATABASE_ADAPTERS_CREDENTIALS_USER: my_db_user
      DOMAIN_CORE_DATABASE_ADAPTERS_CREDENTIALS_PASSWORD: my_db_password
      DOMAIN_CORE_DATABASE_ADAPTERS_CREDENTIALS_DB_NAME: my_db

      #mysql
      #DOMAIN_CORE_DATABASE_ADAPTERS_CREDENTIALS_HOST: db_in_mysql

      #postgres
      DOMAIN_CORE_DATABASE_ADAPTERS_CREDENTIALS_HOST: db_in_postgres

      #sqlite
      #DOMAIN_CORE_DATABASE_ADAPTERS_CREDENTIALS_HOST: /app/my_db.sqlite3
    volumes:
      - ./:/app
    ports:
      - 3000:3000
