version: '3'
services:
  db_in_postgres:
    restart: always
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: my_db_user
      POSTGRES_DB: my_db
      POSTGRES_PASSWORD: my_db_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  db_in_mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'my_db_user'
      MYSQL_PASSWORD: 'my_db_password'
      MYSQL_ROOT_PASSWORD: 'my_db_root_password'
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  ruby-environment:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 3001:3001
    command: /bin/bash -c "tail -f /dev/null"
